version: "{build}"

environment:
  SFTP_USER:
    secure: "uBUgFeI9sHRv0IiMPpA9rg=="
  SFTP_PASSWORD:
    secure: "gXqhlT/yjiLd/jTpvg4kcZtBRCZ8RnoOJ3zRTSF5voA="
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR_NAME: Visual Studio 14 2015
      RUST_TARGET: i686-pc-windows-msvc
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR_NAME: Visual Studio 15 2017 Win64
      RUST_TARGET: x86_64-pc-windows-msvc

branches:
  only:
    - master

matrix:
  fast_finish: true

clone_folder: c:\projects\ja2-stracciatella
clone_depth: 1

init:
  - ps: $env:PUBLISH_BINARY = "false";
  - ps: $env:BUILD_TYPE = "Debug";

  - ps: >
        if (Test-Path Env:\APPVEYOR_PULL_REQUEST_NUMBER) {
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "pull-requests/${env:APPVEYOR_PULL_REQUEST_NUMBER}";
          $env:VERSION_TAG = "${env:APPVEYOR_PULL_REQUEST_NUMBER}pullrequest";
        }
        true;
  - ps: >
        if (Test-Path Env:\NIGHTLY_VERSION) {
          $env:BUILD_TYPE = "Release";
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "nightlies";
          $env:VERSION_TAG = "${env:NIGHTLY_VERSION}";
        }
        true;
  - ps: >
        if ("$env:APPVEYOR_REPO_TAG" -eq "true") {
          $env:BUILD_TYPE = "Release";
          $env:PUBLISH_BINARY = "true";
          $env:PUBLISH_DIR = "releases";
          $env:VERSION_TAG = "";
        }
        true;

  - ps: $env:BUILD_SWITCHES = "-DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DVERSION_TAG=%VERSION_TAG% -DCPACK_GENERATOR=ZIP;NSIS -DCMAKE_TOOLCHAIN_FILE=./cmake/toolchain-msvc.cmake"

  - cmd: echo "%CMAKE_GENERATOR_NAME%"

  - cmd: echo "%PUBLISH_BINARY%"
  - cmd: echo "%PUBLISH_DIR%"
  - cmd: echo "%BUILD_SWITCHES%"

install:
  - ps: $rustVersion = Get-Content .\rust-toolchain -Raw
  - ps: $env:RUSTUP_TOOLCHAIN = "${rustVersion}-${env:RUST_TARGET}";

  - cmd: curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - cmd: rustup-init.exe -y --default-toolchain %RUSTUP_TOOLCHAIN%
  - cmd: set PATH=%PATH%;C:\Users\appveyor\.cargo\bin

  - cmd: echo "%RUSTUP_TOOLCHAIN%"
  - cmd: rustc -V
  - cmd: cargo -V
  - cmd: cmake --version

before_build:
  - cmd: mkdir ci-build
  - cmd: cd ci-build
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" cmake %BUILD_SWITCHES% ..

build_script:
  - ps: cmake --build c:\projects\ja2-stracciatella\ci-build --target ALL_BUILD --config ${env:BUILD_TYPE}

test_script:
  - cmd: cd ..\rust
  - cmd: cargo test
  - cmd: cd ..\ci-build
  - cmd: cd %BUILD_TYPE%
  - cmd: ja2.exe -unittests
  - cmd: ja2-launcher.exe -help

after_test:
  - ps: cmake --build c:\projects\ja2-stracciatella\ci-build --target package
  - ps: >
          if ("$env:PUBLISH_BINARY" -eq "true" -and (Test-Path Env:\SFTP_PASSWORD)) {
            $binary_paths = Get-ChildItem c:\projects\ja2-stracciatella\ci-build\ja2-stracciatella_*;
            foreach ($file in $binary_paths) {
              iex "curl.exe --ftp-create-dirs -T ${file} --ftp-ssl -u ${env:SFTP_USER}:${env:SFTP_PASSWORD} ftp://www61.your-server.de/${env:PUBLISH_DIR}/"
            }
          }

artifacts:
  - path: ci-build\ja2-stracciatella_*
